version: '3'

services:

  web:
    image: educar
#    volumes:
#      - ./:/var/www/html
    ports:
      - 8080:80
    environment:
      DB_CONNECTION: 'pgsql'
      DB_HOST: 'postgres'
      DB_PORT: '5432'
      DB_DATABASE: 'ieducar'
      DB_USERNAME: 'ieducar'
      DB_PASSWORD: 'ieducar'
    links:
      - postgres
      - redis

  postgres:
    container_name: ieducar-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: ieducar
      POSTGRES_USER: ieducar
      POSTGRES_PASSWORD: ieducar
    ports:
      - 5432
#    volumes:
#      - ./database/data:/var/lib/postgresql/data

  redis:
    container_name: ieducar-redis
    image: redis:alpine
    restart: always
    ports:
      - 6379
