version: '3'

services:

  web:
    container_name: ieducar-softagon
    image: i-educar:beta
    volumes:
      - ./:/var/www/html:rw
    ports:
      - 8080:80
    networks:
      - softagon
    environment:
      DB_CONNECTION: 'pgsql'
      DB_HOST: 'postgres'
      DB_PORT: '5432'
      DB_DATABASE: 'araripina'
      DB_USERNAME: 'ieducar'
      DB_PASSWORD: 'ieducar'

      API_ACCESS_KEY: 'softagon'
      API_SECRET_KEY: 'fjIniRGr2@3H'

    links:
      - postgres
      - redis
  postgres:
    container_name: ieducar-postgres
    image: postgres:13.6-alpine
    environment:
      POSTGRES_DB: araripina
      POSTGRES_USER: ieducar
      POSTGRES_PASSWORD: ieducar
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - softagon
  redis:
    container_name: ieducar-redis
    image: redis:alpine
    restart: always
    ports:
      - 6379
    networks:
      - softagon
  directus:
    container_name: ieducar-directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - softagon
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'postgres'
      DB_PORT: '5432'
      DB_DATABASE: 'araripina'
      DB_USER: 'ieducar'
      DB_PASSWORD: 'ieducar'
      DB_SEARCH_PATH: 'cadastro'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
      # Make sure to set this in production
      # (see https://docs.directus.io/configuration/config-options/#general)
      # PUBLIC_URL: 'https://directus.example.com'
volumes:
  pgdata:
networks:
  softagon:
